import { MeetingPlatforms } from "../enums";
import Google_meet from "@/assets/images/google_meet.svg";
import Zoom from "@/assets/images/zoom.svg";
import Other from "@/assets/images/other.svg";
import Microsoft_teams from "@/assets/images/microsoft_teams.svg";
import { DropDownOption, WeekDays } from "@/interfaces";
import { Job } from "../interfaces";
import { IoChevronForward } from "react-icons/io5";

const INTERVAL_START = "9:00 AM";
const INTERVAL_END = "5:00 PM";
export const DEFAULT_INTERVAL = { start: INTERVAL_START, end: INTERVAL_END };

export const COUNTRIES = [
  "United Kingdom",
  "United States",
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia (Czech Republic)",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  'Eswatini (fmr. "Swaziland")',
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar (formerly Burma)",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const CREATE_ACCOUNT_FORMS_DETAIL = [
  {
    name: "AccountSetup",
    displayName: "Account Setup",
    title: "Let’s start!",
    subTitle: "Tell us about yourself.",
  },
  {
    name: "MeetingSoftware",
    displayName: "Meeting Software",
    title: "Hi {{name}}!",
    subTitle: "Where do you like to meet?",
  },
  {
    name: "AvailableHours",
    displayName: "Available Hours",
    title: "Hi {{name}}!",
    subTitle: "What are your working hours?",
  },
  {
    name: "Calendars",
    displayName: "Calendars",
    title: "Hi {{name}}!",
    subTitle: "Let’s connect your calendars.",
  },
];

export const platforms_data = [
  {
    title: MeetingPlatforms.GOOGLE_MEET,
    isRequiredLink: false,
    isShow: false,
    svg: Google_meet,
  },
  {
    title: MeetingPlatforms.MICROSOFT_TEAMS,
    isRequiredLink: false,
    isShow: false,
    svg: Microsoft_teams,
  },
  {
    title: MeetingPlatforms.ZOOM,
    isRequiredLink: true,
    isShow: true,
    svg: Zoom,
  },
  {
    title: MeetingPlatforms.OTHER,
    isRequiredLink: true,
    isShow: true,
    svg: Other,
  },
];

export const DAY_HOURS_DATA = [
  "12:00 AM",
  "12:30 AM",
  "1:00 AM",
  "1:30 AM",
  "2:00 AM",
  "2:30 AM",
  "3:00 AM",
  "3:30 AM",
  "4:00 AM",
  "4:30 AM",
  "5:00 AM",
  "5:30 AM",
  "6:00 AM",
  "6:30 AM",
  "7:00 AM",
  "7:30 AM",
  "8:00 AM",
  "8:30 AM",
  "9:00 AM",
  "9:30 AM",
  "10:00 AM",
  "10:30 AM",
  "11:00 AM",
  "11:30 AM",
  "12:00 PM",
  "12:30 PM",
  "1:00 PM",
  "1:30 PM",
  "2:00 PM",
  "2:30 PM",
  "3:00 PM",
  "3:30 PM",
  "4:00 PM",
  "4:30 PM",
  "5:00 PM",
  "5:30 PM",
  "6:00 PM",
  "6:30 PM",
  "7:00 PM",
  "7:30 PM",
  "8:00 PM",
  "8:30 PM",
  "9:00 PM",
  "9:30 PM",
  "10:00 PM",
  "10:30 PM",
  "11:00 PM",
  "11:30 PM",
];

export const AVAILABLE_SLOTS = [
  { time: "9:00 AM - 10:00 AM", isSelected: false },
  { time: "10:00 AM - 11:00 AM", isSelected: false },
  { time: "11:00 AM - 12:00 PM", isSelected: false },
  { time: "12:00 PM - 1:00 PM", isSelected: false },
  { time: "1:00 PM - 2:00 PM", isSelected: false },
  { time: "2:00 PM - 3:00 PM", isSelected: false },
  { time: "3:00 PM - 4:00 PM", isSelected: false },
  { time: "4:00 PM - 5:00 PM", isSelected: false },
  { time: "5:00 PM - 6:00 PM", isSelected: false },
  { time: "6:00 PM - 7:00 PM", isSelected: false },
  { time: "8:00 PM - 9:00 PM", isSelected: false },
  { time: "9:00 PM - 10:00 PM", isSelected: false },
  { time: "10:00 PM - 11:00 PM", isSelected: false },
  { time: "11:00 PM - 12:00 AM", isSelected: false },
  { time: "1:00 AM - 2:00 AM", isSelected: false },
  { time: "2:00 AM - 3:00 AM", isSelected: false },
  { time: "3:00 AM - 4:00 AM", isSelected: false },
  { time: "4:00 AM - 5:00 AM", isSelected: false },
  { time: "5:00 AM - 6:00 AM", isSelected: false },
  { time: "6:00 AM - 7:00 AM", isSelected: false },
  { time: "7:00 AM - 8:00 AM", isSelected: false },
];

export const jobTitles: Job = {
  SEND_EMAIL: {
    key: "SEND_EMAIL",
    value: "Send Email",
    id: 1,
    type: "send_email",
    isEnabled: false,
    title: "Email",
    isButton: true,
  },
  SEND_FOLLOW_UP_EMAIL: {
    key: "SEND_FOLLOW_UP_EMAIL",
    value: "Send Follow-Up Email",
    id: 2,
    type: "send_follow_up_email",
    isEnabled: false,
    title: "Follow Up",
    isButton: true,
  },

  REFERRAL: {
    key: "REFERRAL",
    value: "Process Referral",
    id: 3,
    type: "referral",
    isEnabled: false,
    title: "Referral",
    isButton: true,
  },
  meeting: {
    key: "meeting",
    value: "Schedule Meeting",
    valueTwo: "Schedule Demo Day",
    id: 4,
    type: "meeting",
    isEnabled: false,
    title: "Meetings",
    isButton: true,
  },
  CREATE_MEETING: {
    key: "meeting",
    value: "Schedule Meeting",
    valueTwo: "Schedule Demo Day",
    id: 5,
    type: "meeting",
    isEnabled: false,
    title: "Meetings",
    isButton: false,
  },
  SCHEDULE_FOLLOW_UP: {
    key: "SCHEDULE_FOLLOW_UP",
    value: "Schedule Follow Up",
    id: 6,
    type: "schedule_follow_up",
    isEnabled: false,
    title: "Follow Up",
    isButton: false,
  },
  PUT_ON_HOLD: {
    key: "PUT_ON_HOLD",
    value: "Follow Up ",
    id: 7,
    type: "put_on_hold",
    isEnabled: false,
    title: "Put on Hold",
    isButton: false,
  },
};

export const WEEK_DAYS_DATA: WeekDays[] = [
  {
    name: "Monday",
    key: "MON",
    hoursInterval: [DEFAULT_INTERVAL],
    isActive: true,
    isEditable: true,
  },
  {
    name: "Tuesday",
    key: "TUE",
    hoursInterval: [DEFAULT_INTERVAL],
    isActive: true,
    isEditable: true,
  },
  {
    name: "Wednesday",
    key: "WED",
    hoursInterval: [DEFAULT_INTERVAL],
    isActive: true,
    isEditable: true,
  },
  {
    name: "Thursday",
    key: "THU",
    hoursInterval: [DEFAULT_INTERVAL],
    isActive: true,
    isEditable: true,
  },
  {
    name: "Friday",
    key: "FRI",
    hoursInterval: [DEFAULT_INTERVAL],
    isActive: true,
    isEditable: true,
  },
  {
    name: "Saturday",
    key: "SAT",
    hoursInterval: [DEFAULT_INTERVAL],
    isActive: false,
    isEditable: true,
  },
  {
    name: "Sunday",
    key: "SUN",
    hoursInterval: [DEFAULT_INTERVAL],
    isActive: false,
    isEditable: true,
  },
];

export const ActionsDropdownOptionsHI: DropDownOption[] = [
  //{ label: "Approve All Jobs ", value: "action0" },
  { label: "Mark as Do Not Contact ", value: "action1" },
  { label: "Mark as Do Not Respond ", value: "action3" },

  {
    label: "Mark as Undelivered",
    value: "action2",
    icon: <IoChevronForward />,
  },
  // { label: "Mark to Handle Later", value: "action3" },
  // { label: "Resend to AI ", value: "action4" },
  // { label: "Raise an issue in Github", value: "action5" },
];

export const ActionsDropdownSubOptionsHI: DropDownOption[] = [
  { label: "Sending Limits", value: "sending limit" },
  { label: "Message Blocked", value: "message blocked" },
  { label: "Invalid Address", value: "invalid address" },
];

export const STATIC_ORGANIZATION_ID = 8