/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hU6XWYR3gXE
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import {
  useCreateAvatarOperation,
  useFetchAvatars,
  useUpdateAvatar,
} from "@/app/nextapi/avatars/api";
import { AvatarData, AvatarPermissionType } from "@/app/nextapi/avatars/models";
import {
  useCreateConversation,
  useFetchConversationsOnDemand,
} from "@/app/nextapi/conversations/api";
import { useCreateAvatarInvitation } from "@/app/nextapi/invitations/api";
import { UserInfoData } from "@/app/nextapi/users/models";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import Button from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { v0props } from "@/lib/utils";
import { useAuth } from "@clerk/nextjs";
import { sendGAEvent } from "@next/third-parties/google";
import Link from "next/link";
import { useRouter } from "next/navigation";
import AvatarSharingDialog, {
  useAvatarSharingDialog,
} from "./avatar-sharing-dialog";

export function AvatarList() {
  const {
    data: avatars = [],
    isLoading: isAvatarsLoading,
    error: avatarsError,
    refetch: refetchAvatars,
  } = useFetchAvatars();

  const { fetchConversations } = useFetchConversationsOnDemand();
  const { mutateAsync: createConversation } = useCreateConversation();
  const { mutateAsync: createAvatarInvitation } = useCreateAvatarInvitation();
  const { mutateAsync: createAvatarOperation } = useCreateAvatarOperation();

  const { userId } = useAuth();
  const router = useRouter();
  const { onOpen: onAvatarSharingOpen, onClose: closeAvatarSharing } =
    useAvatarSharingDialog();

  const error = avatarsError;

  if (error) {
    return <div className="text-red-500">Error: {error.message}</div>;
  }

  if (isAvatarsLoading) {
    return <div>Loading...</div>;
  }

  if (!avatars.length) {
    return <div>No avatars found</div>;
  }

  const launchContribConversation = async (avatar: AvatarData) => {
    sendGAEvent("event", "avatar_conversation_mode_selected", {
      user_id: userId,
      avatar_id: avatar.id,
      conversation_type: "contribution",
    });

    var conversations = await fetchConversations(avatar.id);
    var conversation = conversations.find(
      (item) => item.type === "contribution"
    );

    if (!conversation) {
      conversation = await createConversation({
        avatarId: avatar.id,
        data: {
          type: "contribution",
          description: "",
          title: "",
        },
      });
    }

    router.push(
      `/interact?avatarId=${avatar.id}&convId=${conversation.id}&isContrib=true`
    );
  };

  const launchInteractionConversation = async (avatar: AvatarData) => {
    sendGAEvent("event", "avatar_conversation_mode_selected", {
      user_id: userId,
      avatar_id: avatar.id,
      conversation_type: "interaction",
    });

    var conversations = await fetchConversations(avatar.id);
    var conversation = conversations.find(
      (item) => item.type === "interaction"
    );

    if (!conversation) {
      conversation = await createConversation({
        avatarId: avatar.id,
        data: {
          type: "interaction",
          description: "",
          title: "",
        },
      });
    }

    router.push(
      `/interact?avatarId=${avatar.id}&convId=${conversation.id}&isContrib=false`
    );
  };

  const generateInvitationLink = async (
    avatar: AvatarData,
    permissions: AvatarPermissionType,
    email: string
  ) => {
    sendGAEvent("event", "avatar_invitation_creation_requested", {
      user_id: userId,
      avatar_id: avatar.id,
      permissions: permissions,
    });

    const invitation = await createAvatarInvitation({
      avatarId: avatar.id,
      data: {
        permissions,
        email,
      },
    });

    sendGAEvent("event", "avatar_invitation_created", {
      user_id: userId,
      avatar_id: avatar.id,
      invitation_id: invitation.id,
      permissions: permissions,
    });
    return `${window.location.protocol}://${window.location.hostname}:${window.location.port}/invitation/?id=${invitation.id}&avatarId=${avatar.id}`;
  };

  const removeUserPermission = async (
    avatar: AvatarData,
    user: UserInfoData
  ) => {
    sendGAEvent("event", "avatar_permission_removal_requested", {
      user_id: userId,
      avatar_id: avatar.id,
      permission_user_id: user.id,
    });

    await createAvatarOperation({
      avatarId: avatar.id,
      data: {
        operationType: "removeUserPermission",
        removeUserPermission: {
          userId: user.id,
        },
      },
    });

    if (userId === user.id) {
      await refetchAvatars();
      closeAvatarSharing();
    }

    sendGAEvent("event", "avatar_permission_removed", {
      user_id: userId,
      avatar_id: avatar.id,
      permission_user_id: user.id,
    });
  };

  const updateUserPermission = async (
    avatar: AvatarData,
    user: UserInfoData,
    permissions: AvatarPermissionType
  ) => {
    sendGAEvent("event", "avatar_permission_update_requested", {
      user_id: userId,
      avatar_id: avatar.id,
      permission_user_id: user.id,
    });

    await createAvatarOperation({
      avatarId: avatar.id,
      data: {
        operationType: "updateUserPermission",
        updateUserPermission: {
          userId: user.id,
          permissions,
        },
      },
    });

    sendGAEvent("event", "avatar_permission_updated", {
      user_id: userId,
      avatar_id: avatar.id,
      permission_user_id: user.id,
    });

    return avatar;
  };

  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <AvatarSharingDialog
        onGenerateLink={async (avatar, permissions) => {
          return await generateInvitationLink(avatar, permissions, "");
        }}
        onRemoveUserPermission={async (avatar, user) => {
          await removeUserPermission(avatar, user);
        }}
        onUpdateUserPermission={async (avatar, user, permissions) => {
          await updateUserPermission(avatar, user, permissions);
        }}
        onClosed={async () => {
          await refetchAvatars();
        }}
      />

      <div className="grid gap-6">
        <div className="flex items-center justify-between">
          <h2 className="text-2xl font-bold">People</h2>
          <Link
            href="#"
            className="text-primary hover:underline"
            prefetch={false}
          >
            View all
          </Link>
        </div>
        <div className="grid gap-4">
          {avatars.map((avatar: AvatarData) => (
            <div
              key={avatar.id}
              className="flex items-center gap-4 border rounded-lg p-4"
            >
              <Button
                onClick={() => launchInteractionConversation(avatar)}
                disabled={!avatar.accessControl.canInteract}
              >
                <Avatar className="h-10 w-10">
                  <AvatarImage src="/placeholder-user.jpg" />
                  <AvatarFallback>JD</AvatarFallback>
                </Avatar>
                <div>
                  <h3 className="font-medium">{avatar.characterCard.data.name}</h3>
                </div>
              </Button>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="ghost" size="icon">
                    <MenuIcon className="h-5 w-5" />
                    <span className="sr-only">More options</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuItem
                    disabled={!avatar.accessControl.canContribute}
                  >
                    <Button
                      onClick={() => launchContribConversation(avatar)}
                      className="flex items-center gap-2"
                    >
                      <CircleUserIcon className="h-4 w-4" />
                      <span>Contribute Memories</span>
                    </Button>
                  </DropdownMenuItem>
                  <DropdownMenuItem>
                    <Link
                      href="#"
                      className="flex items-center gap-2"
                      prefetch={false}
                    >
                      <MailIcon className="h-4 w-4" />
                      <span>Settings</span>
                    </Link>
                  </DropdownMenuItem>
                  <DropdownMenuItem>
                    <Button
                      onClick={() => onAvatarSharingOpen(avatar.id)}
                      className="flex items-center gap-2"
                    >
                      <ShareIcon className="h-4 w-4" />
                      <span>Share</span>
                    </Button>
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function CircleUserIcon(props: v0props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="10" r="3" />
      <path d="M7 20.662V19a2 2 0 0 1 2-2h6a2 2 0 0 1 2 2v1.662" />
    </svg>
  );
}

function MailIcon(props: v0props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  );
}

function MenuIcon(props: v0props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function ShareIcon(props: v0props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <polyline points="16 6 12 2 8 6" />
      <line x1="12" x2="12" y1="2" y2="15" />
    </svg>
  );
}
