/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qkaKgzwBMJg
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import React, { useEffect, useRef, useState } from "react";
import Button from "@/components/ui/button";
import { SpeechBubble } from "@/components/ui/speechbubble";
import { Textarea } from "@/components/ui/textarea";
import { v0props } from "@/lib/utils";
import { useAuth } from "@clerk/nextjs";
import { sendGAEvent } from "@next/third-parties/google";
import { useRouter } from "next/navigation";
import useAudioRecorder from "./use-audio-recorder";
import { useChat } from "./use-chat";
import useSpeechToText from "./use-speech-to-text";
import useTextToSpeech from "./use-text-to-speech";
import ConversationFileUpload, {
  UploadedFile,
} from "./conversation-file-upload";
import { ConversationFile } from "./conversation-file";
import {
  useCreateConversation,
  useFetchConversationsOnDemand,
} from "@/app/nextapi/conversations/api";
import {
  AvatarConversationData,
} from "@/app/nextapi/conversations/models";

interface ConversationFileUploadRef {
  clearFiles: () => void;
}

type Props = {
  avatarId: string;
  conversationId: string;
  isContrib: string;
};

export function ChatView(props: Props) {
  const { userId } = useAuth();
  const { avatarId, conversationId } = props;
  const { fetchConversations } = useFetchConversationsOnDemand();
  const { mutateAsync: createConversation } = useCreateConversation();
  const router = useRouter();

  const audioRef = useRef<HTMLAudioElement>(null);
  const { transcribeAudio } = useSpeechToText({
    onTranscriptionCompleted: async (transcription: string) => {
      submitPrompt(transcription);
    },
  });
  const onRecordingStarted = () => {
    sendGAEvent("event", "conversation_voice_recording_started", {
      ...gaEventContext,
    });
  };

  const onRecordingStopped = (audioBlob: Blob) => {
    sendGAEvent("event", "conversation_voice_recording_stopped", {
      ...gaEventContext,
    });

    transcribeAudio(audioBlob);
  };

  const onRecordingError = (error: string) => {
    sendGAEvent("event", "conversation_voice_recording_error", {
      ...gaEventContext,
    });
    alert("Make sure you gave permission to record audio.");
  };

  const {
    isRecording,
    audioBlob,
    error: recordingError,
    startRecording,
    stopRecording,
    resetRecorder,
  } = useAudioRecorder({
    onRecordingStarted,
    onRecordingStopped,
    onRecordingError,
  });

  const { generateSpeech } = useTextToSpeech();

  const [uploadedFiles, setUploadedFiles] = useState<UploadedFile[]>([]);
  const conversationFileUploadRef = useRef<ConversationFileUploadRef>(null);

  const inputContainerRef = useRef<HTMLDivElement>(null); // Type the ref as HTMLDivElement
  const messageContainerRef = useRef<HTMLDivElement>(null); // Type the ref as HTMLDivElement
  const contributionConversation = useRef<AvatarConversationData>();

  useEffect(() => {
    async function getContributionConversation() {
      // You can await here
      var conversations = await fetchConversations(avatarId);
      contributionConversation.current = conversations.find(
        (item) => item.type === "contribution"
      );
      // ...
    }
    getContributionConversation();

    const adjustMessageContainerPadding = () => {
      if (inputContainerRef.current && messageContainerRef.current) {
        const inputHeight = inputContainerRef.current.offsetHeight;
        messageContainerRef.current.style.paddingBottom =  `calc(${inputHeight + 100}px)`; // Adjust height dynamically
      }
    };

    adjustMessageContainerPadding();
    window.addEventListener("resize", adjustMessageContainerPadding);

    return () => {
      window.removeEventListener("resize", adjustMessageContainerPadding);
    };
  }, [avatarId, fetchConversations]);

  const { avatar, conversation, messages, isLoading, submitPrompt } = useChat(
    avatarId,
    conversationId,
    {
      onPromptResponseReceived: async (messages) => {
        var assistantMessage = messages
          .find((m) => m.messageType.label === "assistant")
          ?.items.map((i) => (i.$type === "text" ? i.content : ""))
          .join(" ");

        if (assistantMessage && conversation!.type === "contribution" ||
          (avatar && avatar.voice)) {
          playbackTextToSpeech(assistantMessage!, conversation!.type === "contribution" ? "g4sVu5zE1rLkKGVDKKCy" : avatar!.voice);
        }
      },
    }
  );
  const [currentPrompt, setCurrentPrompt] = useState("");

  const clearUploadedFiles = () => {
    if (conversationFileUploadRef.current) {
      conversationFileUploadRef.current.clearFiles();
    }
  };

  const playbackTextToSpeech = async (text: string, voice: string) => {
    try {
      const audioBuffer = await generateSpeech(text, voice);
      const base64Audio = audioBuffer.toString("base64");
      const dataUrl = `data:audio/mpeg;base64,${base64Audio}`;

      if (audioRef.current) {
        audioRef.current.src = dataUrl;
        audioRef.current.play();
      }
    } catch (error) {
      console.error("Error generating speech:", error);
    }
  };

  const createUpdatedConversation = async () => {
    sendGAEvent("event", "avatar_conversation_regenerate", {
      user_id: userId,
      avatar_id: avatarId,
      conversation_type: "interaction",
    });

    var conversation = await createConversation({
      avatarId: avatarId,
      data: {
        type: "interaction",
        description: "",
        title: "",
      },
    });

    router.push(
      `/interact?avatarId=${avatarId}&convId=${conversation.id}&isContrib=false`
    );
  };

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (!avatar || !conversation || !messages) {
    return <div>Part of the conversation was not loaded...</div>;
  }

  const gaEventContext = {
    user_id: userId,
    avatar_id: avatarId,
    conversation_id: conversationId,
    conversation_type: conversation.type,
  };

  const messagesComponent = messages.map((m) => {
    var textContent = m.items
      .map((i) => (i.$type === "text" ? i.content : ""))
      .join(" ");
    return (
      <>
        <SpeechBubble
          key={m.id}
          isUserMessage={m.messageType.label === "user"}
          message={textContent}
        />
        {m.items
          .filter((i) => i.$type === "file")
          .map((f) => (
            <ConversationFile
              key={f.file.fileId}
              avatarId={avatarId}
              content={f}
            />
          ))}
      </>
    );
  });

  var canConverse =
    (conversation.type === "contribution" && avatar.accessControl.canContribute) ||
    (conversation.type === "interaction" && avatar.accessControl.canInteract);

  return (
    <div className="w-full h-screen bg-white dark:bg-gray-950 flex flex-col">
      <span>
        {avatar.characterCard.data.name} ({conversation.type})
        <br/>
        {conversation.syncedContributionMessagesAt.toLocaleString()}
        <br/>
        <Button onClick={() => createUpdatedConversation()}>
          Generate new chat
        </Button>
        {contributionConversation.current != null &&
         conversation.syncedContributionMessagesAt < contributionConversation.current?.syncedContributionMessagesAt ?
          "Updated memories available!  Generate a new chat to get the latest changes." : null}
      </span>
      <div
        ref={messageContainerRef}
        className="flex-1 overflow-y-auto p-6 space-y-4"
      >
        {messagesComponent}
        <audio ref={audioRef}></audio>
      </div>
      <div
        ref={inputContainerRef}
        className="border-t border-gray-200 dark:border-gray-800 py-4 w-full bg-white dark:bg-gray-950 fixed bottom-0 left-0 z-10"
      >
        <div className="relative">
          <form
            onSubmit={(event) => {
              event.preventDefault();
              sendGAEvent("event", "conversation_message_submitted", {
                ...gaEventContext,
              });
              submitPrompt(
                currentPrompt,
                uploadedFiles.map((f) => ({
                  fileId: f.fileId!,
                }))
              );
              setCurrentPrompt("");
              clearUploadedFiles();
            }}
          >
            <Textarea
              value={currentPrompt}
              onChange={(event) => setCurrentPrompt(event.target.value)}
              id="chatbox"
              placeholder="Say something..."
              rows={3}
              disabled={!canConverse}
              className="w-full resize-none overflow-hidden min-h-[3rem] max-h-[10rem]"
              style={{ height: 'auto' }} // Auto height for initial sizing
              onInput={(e) => {
                const target = e.currentTarget;
                target.style.height = "auto";
                target.style.height = `${target.scrollHeight}px`;
                if (inputContainerRef.current && messageContainerRef.current) {
                  const inputHeight = inputContainerRef.current.offsetHeight;
                  messageContainerRef.current.style.paddingBottom = `calc(${inputHeight+100}px)`; // Adjust height dynamically
                }
              }} // Auto-resizing script
            />
            <Button
              type="submit"
              size="icon"
              className="absolute top-3 right-12 w-8 h-8"
              disabled={!canConverse}
            >
              <ArrowUpIcon className="w-4 h-4" />
              <span className="sr-only">Send</span>
            </Button>
            <Button
              type="button"
              size="icon"
              className="absolute top-3 right-3 w-8 h-8"
              disabled={!canConverse}
              onClick={() => {
                if (isRecording) {
                  stopRecording();
                } else {
                  startRecording();
                }
              }}
            >
              {isRecording ? (
                <MicMuteIcon className="w-4 h-4" />
              ) : (
                <MicIcon className="w-4 h-4" />
              )}
              <span className="sr-only">Record</span>
            </Button>
            <ConversationFileUpload
              avatarId={avatarId}
              conversationId={conversationId}
              onFilesUploaded={(files) => setUploadedFiles(files)}
              ref={conversationFileUploadRef}
            />
          </form>
        </div>
      </div>
    </div>
  );
}

function ArrowUpIcon(props: v0props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m5 12 7-7 7 7" />
      <path d="M12 19V5" />
    </svg>
  );
}

function MoveHorizontalIcon(props: v0props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="18 8 22 12 18 16" />
      <polyline points="6 8 2 12 6 16" />
      <line x1="2" x2="22" y1="12" y2="12" />
    </svg>
  );
}

function SearchIcon(props: v0props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function MicIcon(props: v0props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
      <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
      <line x1="12" x2="12" y1="19" y2="22" />
    </svg>
  );
}

function MicMuteIcon(props: v0props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
      <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
      <line x1="12" x2="12" y1="19" y2="22" />
      <line x1="1" y1="1" x2="23" y2="23" /> {/* Line indicating mute */}
    </svg>
  );
}
